version: '3'

services:

  nginx:
    container_name: eicaa_frontend
    build: .
    image: eicaa-frontend:latest
    env_file: ./.env
    restart: unless-stopped
    ports:
      - 127.0.0.1:8080:3000
    networks:
      - eicaa

networks:
  eicaa:
    name: "eicaa-network"
    ipam:
      driver: default
      config:
      - subnet: "172.99.0.0/24"
